CITIES = cities = [
    "Tokyo",
    "New Delhi",
    "Paris",
    "London",
    "Washington, D.C.",
    "Beijing",
    "Moscow",
    "Berlin",
    "Rome",
    "Brasília",
    "Ottawa",
    "Cairo",
    "Canberra",
    "Madrid",
    "Stockholm",
    "Buenos Aires",
    "Islamabad",
    "Nairobi",
    "Oslo",
    "Lisbon",
    "Hanoi",
    "Athens",
    "Dublin",
    "Bangkok",
    "Amsterdam",
    "Riyadh",
    "Mexico City",
    "Bogotá",
    "Vienna",
    "Copenhagen",
    "Wellington",
    "Brussels",
    "Ankara",
    "Tehran",
    "Lima",
    "Warsaw",
    "Kabul",
    "Santiago",
    "Doha",
    "Kuala Lumpur",
    "Nicosia",
    "Helsinki",
    "Ljubljana",
    "Addis Ababa",
    "Kiev",
    "Nassau",
    "Manila",
    "Budapest",
    "Cape Town",
    "New York City",
    "Los Angeles",
    "Tokyo",
    "Paris",
    "Sydney",
    "Toronto",
    "Mumbai",
    "Rio de Janeiro",
    "Barcelona",
    "Chicago",
    "Dubai",
    "Singapore",
    "Shanghai",
    "San Francisco",
    "Berlin",
    "Istanbul",
    "Amsterdam",
    "Seoul",
    "Miami",
    "Hong Kong",
    "Marrakech",
    "Cape Town",
    "Montreal",
    "Auckland",
    "Vancouver",
    "Stockholm",
    "Osaka",
    "Buenos Aires",
    "Munich",
    "Bangkok",
    "Moscow",
    "Lisbon",
    "Cairo",
    "Delhi",
    "Barcelona",
    "Rome",
    "Helsinki",
    "Nairobi",
    "Copenhagen",
    "Kuala Lumpur",
    "Bogotá",
    "Mexico City",
    "Vienna",
    "Prague",
    "Dublin",
    "Johannesburg",
    "Seville",
    "Warsaw",
    "Brussels",
    "Hanoi",
]
